language: go


cache:
  directories:
    - $GOPATH/pkg/dep

env:
  - DEP_VERSION="0.4.1"

before_install:

  # Setup some env variables
  - GO_FILES=$(find . -iname '*.go' | grep -v /vendor/)  # All the .go files, excluding vendor/
  - PKGS=$(go list ./... | grep -v /vendor/ |grep -v /cmd/)             # All the import paths, excluding vendor/
  
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

  # Install linters
  - go get -u honnef.co/go/tools/cmd/megacheck
  - go get -u honnef.co/go/tools/cmd/unused
  - go get -u github.com/mattn/goveralls

install:
  - dep ensure

go:
  - "1.10.2"
  
script:
  - megacheck $PKGS
  - unused $PKGS
  - go test -v -covermode=count -coverprofile=profile.cov $PKGS
  - goveralls -coverprofile=profile.cov -service=travis-ci